# code: language=ansible
---
- name: Setup {{ app }}
  when: not is_mac # MacOSX has yet to need it
  vars:
    app: "rust"
    path: "$HOME/.cargo"

  block:
    - name: "Install {{ app }}"
      become: true
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - {name: "rustc", state: "present"}
        - {name: "cargo", state: "present"}

    - name: Ensure cargo directory exists
      ansible.builtin.file:
        path: "{{ path }}"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
        modification_time: preserve
        access_time: preserve

    - name: Configure {{ file_zshrc }}
      ansible.builtin.blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_zshrc }}"
        backup: true
        block: |
          PATH=$PATH:{{ path }}/bin

          test -f "$(command -v zoxide)" && eval "$(zoxide init bash)"
        prepend_newline: true
        state: present

    - name: Configure {{ file_bashrc }}
      ansible.builtin.blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_bashrc }}"
        backup: true
        block: |
          PATH=$PATH:{{ path }}/bin
        prepend_newline: true
        state: present
