# code: language=ansible
---
- name: Setup computer
  hosts: all

  vars:

  tasks:
    - name: Debug all variables in current scope
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      tags:
        - never
        - debug_info

  roles:
    - role: macos
      when: is_mac

    - bash
    - zsh

    - fzf
    - zoxide

    - vscode
