# code: language=ansible
---
- name: Setup computer
  hosts: all

  vars:
    # Define git repository user
    git_global_configs:
      - { name: "user.name", value: "Ken Wong" }
      - { name: "user.email", value: "canonw@users.noreply.github.com" }

  tasks:
    - name: Debug all variables in current scope
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      tags:
        - never
        - debug_info

  roles:
    - role: macos
      when: is_mac

    - bash
    - zsh

    - git

    - fzf
    - zoxide

    - fastfetch

    - vscode
