# code: language=ansible
---
- name: Setup computer
  hosts: all

  vars:
    # Define git repository user
    git_global_configs_ex:
      - { name: "user.name", value: "Ken Wong" }
      - { name: "user.email", value: "canonw@users.noreply.github.com" }

  tasks:
    - name: Debug facts
      vars:
        msg: |
          Ansible Distribution: {{ ansible_distribution }}
          Ansible Dist Version: {{ ansible_distribution_version }}
          ansible_distribution_major_version: {{ ansible_distribution_major_version }}
          ansible_distribution_release: {{ ansible_distribution_release }}
          ansible_os_family: {{ ansible_os_family }}
          ansible_kernel: {{ ansible_kernel }}
          ansible_user_dir: {{ ansible_user_dir }}
          Ansible User home: {{ ansible_env.HOME }}
          ansible_user_shell: {{ ansible_user_shell }}
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info

    - name: Debug host variables
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
      tags:
        - never
        - debug_info

  roles:
    - role: os-bootstrap

    - bash
    - role: powershell
      when: not is_ubuntu # need manual download
    - zsh

    - dotnet
    - nodejs
    - role: rust
      when: not is_mac # not test

    - volta

    - git

    - role: ansible
    - role: direnv
    - role: xclip
      when: not is_mac # Ubuntu tool
    - fzf
    - role: git-delta
    - lsd
    - zoxide

    - fastfetch
    - navi

    - role: docker
      when: not is_wsl # TODO: test WSL2
    - role: kubernetes
      when: not is_wsl # TODO: test WSL2

    - neovim
    - role: vscode
      when: not is_wsl

    - aws
