# code: language=ansible
---
# An interactive cheatsheet tool for the command-line.
# https://github.com/denisidoro/navi
- name: Setup {{ app }}
  vars:
    app: "navi"
    path: "$HOME/.cargo"
  block:
    - name: Install {{ app }} (Mac)
      when: is_mac
      community.general.homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - {name: "navi", state: "present"}

    - name: Install {{ app }} (Ubuntu)
      when: is_ubuntu
      community.general.cargo:
        name: "{{ item.name }}"
        path: "{{ path }}"
        state: "{{ item.state | default('present') }}"
        locked: true
      with_items:
        - { name: "navi" }

    - name: Create file block header
      ansible.builtin.shell:
        cmd: |
          set -o pipefail # <-- adding this will prevent surprises
          figlet -f {{ figlet_font }} '{{ app }}' | boxes -d {{ boxes_design }}
        executable: /bin/bash
      register: navi_block_header_result
      changed_when: navi_block_header_result.rc != 0

    - name: Configure {{ file_zshrc }}
      ansible.builtin.blockinfile:
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_zshrc }}"
        backup: true
        block: |
          {{ navi_block_header_result.stdout }}
          test -f "$(command -v navi)" && eval "$(navi widget zsh)"
        prepend_newline: true

    - name: Configure {{ file_bashrc }}
      ansible.builtin.blockinfile:
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_bashrc }}"
        backup: true
        block: |
          {{ navi_block_header_result.stdout }}
          test -f "$(command -v navi)" && eval "$(navi widget bash)"
        prepend_newline: true

    - name: Ensure custom configuration directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/navi/cheats"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
        modification_time: preserve
        access_time: preserve
