# code: language=ansible
---
# An interactive cheatsheet tool for the command-line.
# https://github.com/denisidoro/navi
- name: Install navi
  community.general.homebrew:
    name: navi
    state: present

- name: Update {{ file_zshrc }}
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - navi"
    dest: "{{ file_zshrc }}"
    backup: true
    block: |
      test -f "$(command -v navi)" && eval "$(navi widget zsh)"
    prepend_newline: true
    state: present

- name: Update {{ file_bashrc }}
  ansible.builtin.blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK - navi"
    dest: "{{ file_bashrc }}"
    backup: true
    block: |
      test -f "$(command -v navi)" && eval "$(navi widget bash)"
    prepend_newline: true
    state: present

- name: Ensure custom configuration directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/navi/cheats"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
    modification_time: preserve
    access_time: preserve
