# code: language=ansible
---
- name: Setup {{ app }}
  vars:
    app: "direnv"
  block:
    - name: Install {{ app }}
      become: "{{ not is_mac | bool }}"
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - { name: "direnv" }

    - name: Create file block header
      ansible.builtin.shell:
        cmd: |
          set -o pipefail # <-- adding this will prevent surprises
          figlet -f {{ figlet_font }} '{{ app }}' | boxes -d {{ boxes_design }}
        executable: /bin/bash
      register: direnv_block_header_result
      changed_when: direnv_block_header_result.rc != 0

    - name: Configure {{ file_zshrc }}
      ansible.builtin.blockinfile:
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_zshrc }}"
        backup: true
        block: |
          {{ direnv_block_header_result.stdout }}
          test -f "$(command -v direnv)" && eval "$(direnv hook zsh)"
        prepend_newline: true
      tags:
        - never # Handle by Oh My Zsh

    - name: Configure {{ file_bashrc }}
      ansible.builtin.blockinfile:
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_bashrc }}"
        backup: true
        block: |
          {{ direnv_block_header_result.stdout }}
          test -f "$(command -v direnv)" && eval "$(direnv hook bash)"
        prepend_newline: true
