# code: language=ansible
---
- name: Setup {{ app }}
  vars:
    app: "volta"
  block:
    # Include --skip-setup to exclude build-in setup profile
    - name: "Install specific setup for {{ ansible_os_family }}"
      become: false
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl https://get.volta.sh | bash -s -- --skip-setup
      args:
        creates: "{{ ansible_env.HOME }}/.volta/bin/volta" # Prevents re-running if Volta is already installed
