# code: language=ansible
---
# https://dandavison.github.io/delta/
- name: Setup {{ app }}
  when: not is_mac or not is_ubuntu # MacOS needs testing.  Ubuntu needs 24.04
  vars:
    app: "git-delta"
    file_gitconfig: "delta.gitconfig"
  block:
    - name: Install {{ app }}
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}.yml"
          skip: true

    - name: Copy git-delta gitconfig file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/roles/git-delta/files/{{ file_gitconfig }}"
        dest: "{{ my_config_dir }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: "0644"

    - name: Configure .gitconfig
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
        state: "{{ item.state | default('present') }}"
      loop:
        - { name: "include.path", value: "{{ my_config_dir | replace('$HOME', '~') }}{{ file_gitconfig }}" }
