# code: language=ansible
---
- name: Setup {{ app }}
  vars:
    app: "awscli"

  block:
    - name: "Install custom setup for {{ ansible_os_family }}"
      become: "{{ not is_mac | bool }}"
      ansible.builtin.package:
        name: "{{ package_item.name }}"
        state: "{{ package_item.state | default('present') }}"
      loop:
        - { name: "awscli" }
      loop_control:
        loop_var: package_item
