# code: language=ansible
---
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html
- name: Setup {{ app }}
  vars:
    app: "aws"
    cli_path: "{{ ansible_env.HOME }}/.aws/cli"
    aws_code_block:
      # MacOSX: #  brew has completion configured
      #   test -f "$(command -v fzf)" && source <(fzf --zsh)
      # Reference 'apt show fzf'
      Ubuntu: |
        test -f "$(command -v aws_completer)" && complete -C "$(which aws_completer)" aws
  block:
    - name: Install {{ app }}
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - "default.yml"
          skip: true

    - name: Ensure custom configuration directory exists
      ansible.builtin.file:
        path: "{{ cli_path }}"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
        recurse: true
        modification_time: preserve
        access_time: preserve

    - name: Download AWS CLI alias
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/awslabs/awscli-aliases/master/alias"
        dest: "{{ cli_path }}"
        mode: "0644"

    - name: Create file block header
      ansible.builtin.shell:
        cmd: |
          set -o pipefail # <-- adding this will prevent surprises
          figlet -f {{ figlet_font }} '{{ app }}' | boxes -d {{ boxes_design }}
        executable: /bin/bash
      register: aws_block_header_result
      changed_when: aws_block_header_result.rc != 0

    - name: Configure {{ file_zshrc }}
      ansible.builtin.blockinfile:
        state: present
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
        dest: "{{ file_zshrc }}"
        backup: true
        block: |
          {{ aws_block_header_result.stdout }}
          {{ aws_code_block[ansible_distribution] | default('') }}
        prepend_newline: true
      when: aws_code_block[ansible_distribution] is defined

    # Note: Both MacOSX and WSL2 have bash completion configured
    # - name: Configure {{ file_bashrc }}
    #   ansible.builtin.blockinfile:
    #     state: present
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ app }}"
    #     dest: "{{ file_bashrc }}"
    #     backup: true
    #     block: |
    #       {{ aws_block_header_result.stdout }}
    #       {{ aws_block_header_result.stdout }}
    #     prepend_newline: true
