# code: language=ansible
---
- name: Setup {{ app }}
  vars:
    app: "clipboard_project"
    packages:
      - { name: "clipboard" }
  block:
    - name: "Install custom setup for {{ ansible_distribution }}"
      become: true
      community.general.snap:
        name: "{{ package_item.name }}"
        state: "{{ package_item.state | default(omit) }}"
        classic: "{{ package_item.classic | default(omit) }}"
      loop: "{{ packages }}"
      loop_control:
        loop_var: package_item
