# code: language=ansible
---
- name: Setup {{ app }}
  vars:
    app: "powershell"
  block:
    - name: Install {{ app }}
      become: "{{ not is_mac | bool }}"
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - { name: "powershell" }
